---
title: "Dev_Intra_Inter_Prec"
author: "Oliver Speer"
format: html
editor: visual
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
source("StartUp.R")
StartUpRoutine()

```

## SQL query for QC data

```{r, echo=FALSE, warning=FALSE, message=FALSE}

nameQuery <- sprintf("SELECT TestName FROM TranslationData WHERE Methode = '%s'", method)
name <- dbGetQuery(con, nameQuery)[,1]

# enable and register the REGEXP function in the SQLite connection
initExtension(con, extension = "regexp")

# SQL query for intra- and inter-assay precision data
query.L <- sprintf("SELECT TestName, TestStartDT, SampleID, CAST(DoseResult AS FLOAT) AS DoseResult, DoseUnit
                  FROM DxIvalData
                  WHERE TestName = '%s' 
                    AND SampleID REGEXP '[a-zA-Z]+1' --_\\d'
                    AND DoseUnit IS NOT NULL
                  GROUP BY
                    TestStartDT;", name)

query.H <- sprintf("SELECT TestName, TestStartDT, SampleID, CAST(DoseResult AS FLOAT) AS DoseResult, DoseUnit
                  FROM DxIvalData
                  WHERE TestName = '%s' 
                    AND SampleID REGEXP '[a-zA-Z]+2' --_\\d'
                    AND DoseUnit IS NOT NULL;", name)

# execute the query
prc.L.data <- dbGetQuery(con, query.L) 
prc.L.data <-  prc.L.data |>  group_by(Date = as.Date(TestStartDT, format = "%m-%d-%Y")) |> slice_head(n = 5) |> ungroup()
prc.L.data <- head(prc.L.data, 25)

prc.H.data <- dbGetQuery(con, query.H)
prc.H.data <-  prc.H.data |>  group_by(Date = as.Date(TestStartDT, format = "%m-%d-%Y")) |> slice_head(n = 5) |> ungroup()
prc.H.data <- head(prc.H.data, 25)



```

```{r CLSIEP15 table, echo=FALSE, warning=FALSE, message=FALSE}
# building the CLSIEP15 table
L.long <- data.frame(
  rep = rep(1:5, each = 5),
  name = prc.L.data$SampleID[1:25],
  value = prc.L.data$DoseResult[1:25]
)

H.long <- data.frame(
  rep = rep(1:5, each = 5),
  name = prc.H.data$SampleID[1:25],
  value = prc.H.data$DoseResult[1:25]
)

library(CLSIEP15)
prc.data.L <- calculate_aov_infos(L.long)
prc.data.H <- calculate_aov_infos(H.long)

# prec.data <-
#   val.prec |> select(Messwert_intra1,
#                      Messwert_intra2,
#                      Messwert_inter1,
#                      Messwert_inter2)

# prec.data.stat <-
#   prec.data |> summarize(n = n(), across(
#     Messwert_intra1:Messwert_inter2,
#     list(
#       Mittelwert = \(x) round(mean(x, na.rm = TRUE), digits = 2),
#       StabW = \(x) round(sd(x, na.rm = TRUE), digits = 2),
#       VK = \(x) round(cv(x), digits = 1)
#     )
#   ),)

val.prec <- read_excel("vdata _DxI.xlsx", sheet = "PREC")

intra.df <- data.frame(
  "Intra Assay" = c("n", "Zielwert", "Mittelwert", "SD", "VK (%)"),
  L = c(
    paste(prc.data.L$N),
    paste(val.prec$Ziel_intra1[1]),
    paste(round(prc.data.L$mean, 2) ),
    paste(round(prc.data.L$sd, 2) ),
    paste(round(prc.data.L$Vwithin, 2))
  ),
  H = c(
    paste(prc.data.H$N),
    paste(val.prec$Ziel_intra2[1]),
    paste(round(prc.data.H$mean, 2) ),
    paste(round(prc.data.H$sd, 2)),
    paste(round(prc.data.H$Vwithin, 2))
  )
)

inter.df <- data.frame(
  "Inter Assay" = c("n", "Zielwert", "Mittelwert", "SD", "VK (%)"),
  L = c(
    paste(prc.data.L$n),
    paste(val.prec$Ziel_inter1[1]),
    paste(round(prc.data.L$mean, 2)),
    paste(round(prc.data.L$sd, 2)),
    paste(round(prc.data.L$Vbetween), 2)
  ),
  H = c(
    paste(prc.data.H$n),
    paste(val.prec$Ziel_inter2[1]),
    paste(round(prc.data.H$mean), 2),
    paste(round(prc.data.H$sd), 2),
    paste(round(prc.data.H$Vbetween), 2)
  )
)

```
