---
title: "DxI9000Validation"
format: html
editor: visual
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
#prepare libraries
library(readxl)
library(data.table)
library(tidyverse)
library(DBI)
library(RSQLite)

source("StartUp.R")
StartUpRoutine()

```

# Daten einlesen

```{r import valData, warning=FALSE, message=FALSE}
setwd("C:/R_local/autoVal")

# function to rename duplicate column names
# rename_duplicates <- function(data) {
#   names(data) <- make.unique(names(data), sep = "")
#   return(data)
# }
# read DXI data
# val.dat <- read_excel("C:/R_local/autoVal/240521_DXIrawdata.xlsx")
 dir.rawdata <- "I:\\Institut-Haus 04\\Labor 2_Core Lab Klinische Chemie\\Evaluationen\\Geraete\\DxI9000\\Validation\\2_Rohdaten\\"
 
 # List all raw data CSV files
 csv.files <- list.files(path = dir.rawdata, pattern = "*.csv", full.names = TRUE)
 
 # Check if there are any raw data files
 if (length(csv.files) > 0) {
   # Identify the latest file based on modification time
   latest.csv <- csv.files[which.max(file.info(csv.files)$mtime)]
   
   val.dat <- read_csv(latest.csv)
   
   # val.dat <- read_csv("I:\\Institut-Haus 04\\Labor 2_Core Lab Klinische Chemie\\Evaluationen\\Geräte\\DxI9000\\Validation\\2_Rohdaten\\20240527 Messungen 12.csv")
   
   val.dat <- val.dat |>  
     rename(
       PackRevision = `PackRevision...77`,
       PackRevision2 = `PackRevision...89`
     )
   
   setDT(val.dat)
   
   
   val.dat$Probennummer <- as.numeric(substr(val.dat$SampleID, 1, nchar(val.dat$SampleID) - 2))
  #  val.dat$DoseResult <- as.numeric(val.dat$DoseResult)
 }
```

```{r}
 # load mol masses table-----------------------------------------------------------------------------------------------------
 df.mol.mass <- read_excel("C:/R_local/autoVal/Dev_changeUnitsDxI9000.xlsx") # Dev_changeUnitsDxI9000.xlsx written manually
 save(df.mol.mass, file = "mol_mass.RData")
 load("mol_mass.RData")
 
 
 sum.dat <- setDT(df.mol.mass)
 sum.dat$molar_mass <- as.numeric(sum.dat$`molar_mass(g/mol)`)
```
```{r}
df <- data.frame(cbind(val.dat$TestOrderCode, val.dat$TestName, val.dat$DoseResult, val.dat$DoseUnit))

# Rename columns
colnames(df) <- c("TestOrderCode", "TestName", "DoseResult", "DoseUnit")

 # Merge data tables
merged.dat <- merge(df, sum.dat, by = "TestOrderCode", all.x = TRUE)
merged.dat$DoseResult <- as.numeric(merged.dat$DoseResult)
             




```



```{r}
# Function to convert units to a standard form
   convert_to_standard <- function(unit) {
     install_unit("IU", "umol/min", "international unit")
     # Define a dictionary for common unit conversions
     unit_dict <- list(
       "ug/l" = set_units(1, "ug/l"),
             "ng/ml" = set_units(1, "ng/ml"),
             "nmol/l" = set_units(1, "nmol/l"),
             "umol/l" = set_units(1, "umol/l"),
             "pmol/l" = set_units(1, "pmol/l"),
             "ng/l" = set_units(1, "ng/l"),
             "pg/ml" = set_units(1, "pg/ml"),
             "ug/dl" = set_units(1, "ug/dl"),
             "ng/dl" = set_units(1, "ng/dl"),
             "mU/l" = set_units(1, "mIU/l"),
             "mIU/ml" = set_units(1, "mIU/ml"),
             "uIU/ml" = set_units(1, "uIU/ml"),
             "U/l" = set_units(1, "IU/l"),
             "nmol/l" = set_units(1, "nmol/l"),
             "µg/l" = set_units(1, ug/l),
             "ng/mL" = set_units(1, ng/ml),
             "ng/ml" = set_units(1, ng/ml),
             "nmol/l" = set_units(1, nmol/l),
             "µmol/l" = set_units(1, umol/l),
             "pmol/l" = set_units(1, pmol/l),
             "ng/l" = set_units(1, ng/l),
             "pg/mL" = set_units(1, pg/ml),
             "µg/dL" = set_units(1, ug/dl),
             "µg/l" = set_units(1, ug/l),
             "ng/dL" = set_units(1, ng/dl),
             "mU/l" = set_units(1, mIU/l),
             "mlU/l" = set_units(1, mIU/l), # Assumed conversion for demonstration
             "U/l" = set_units(1, IU/l),
             "µIU/mL" = set_units(1, uIU/ml),
             "mIU/mL" = set_units(1, mIU/ml),
             "nmol/L" = set_units(1, nmol/l), # assuming case insensitivity
             "nmol/l" = set_units(1, nmol/l),
             "g/mol" = set_units(1, g/mol)# assuming case insensitivity
           )
         
           # Convert to lowercase to handle case insensitivity
           unit_lower <- tolower(unit)
           
             # Check if unit exists in dictionary
             if (!unit_lower %in% names(unit_dict)) {
                 message(paste("Unit", unit, "not found in dictionary."))
                 return(NULL)
               }
           
             return(unit_dict[[unit_lower]])
         }
```

```{r}
n <- length(merged.dat$DoseResult)
merged.dat$DoseResult_c <- numeric(n)
for (i in 1:n){
    if (is.na(merged.dat$DoseResult[i])) {
      merged.dat$DoseResult_c[i] <- NA
      next
    }
  from_unit <- convert_to_standard(merged.dat$DoseUnit[i])
  to_unit <- convert_to_standard(merged.dat$Einheit_800[i])
  # Compare the units
               is_same_unit <- tryCatch({
                   isTRUE(all.equal(from_unit, to_unit))
                 }, error = function(e) {
                     FALSE
                   })
  if (is_same_unit == FALSE && grepl("mol", units(to_unit)$numerator)) {
    merged.dat$DoseResult_c[i] <- set_units(merged.dat$DoseResult[i], from_unit, mode = "standard") / 
      set_units(merged.dat$molar_mass[i], "g/mol") / 
      set_units(1, merged.dat$Einheit_800[i], mode = "standard")
  #   merged.dat$DoseResult_c[i] <- merged.dat$DoseResult[i]
  # } else if (grepl("mol", to_unit)) {
  #   merged.dat$DoseResult_c[i] <- set_units(merged.dat$DoseResult[i], from_unit) / set_units(merged.dat$molar_mass[i], "g/mol") / set_units(1, merged.dat$Einheit_800[i], mode = "standard")
  } else {
    merged.dat$DoseResult_c[i] <- merged.dat$DoseResult[i]
  }
 }

```



```{r}
 # Function to compare units and convert if necessary
     compare_and_convert_single <- function(dose_results, dose_unit, einheit_800, molar_mass) {
         dose_results <- as.numeric(dose_results)  # Ensure dose_result is numeric
         
           # Convert units to standard form
           standard_from_unit <- tryCatch({
               convert_to_standard(dose_unit)
             }, error = function(e) {
                 return(NULL)
               })
           
             standard_to_unit <- tryCatch({
                 convert_to_standard(einheit_800)
               }, error = function(e) {
                   return(NULL)
                 })
             
               if (is.null(standard_from_unit) || is.null(standard_to_unit)) {
                   message(paste("Unit conversion failed for units:", dose_unit, "and", einheit_800))
                   return(NA)  # Return NA for unrecognized units
                 }
             
               # Compare the units
               is_same_unit <- tryCatch({
                   isTRUE(all.equal(standard_from_unit, standard_to_unit))
                 }, error = function(e) {
                     FALSE
                   })
               
                 # If units are not the same, convert the result to molar concentration
                 if (!is_same_unit) {
                     converted_result <- set_units(dose_results, convert_to_standard(dose_unit), mode = "standard") / 
                         set_units(molar_mass, "g/mol") / 
                         set_units(1, einheit_800, mode = "standard")
                     # converted_result <- convert_to_molar(dose_results, standard_from_unit, molar_mass)
                       return(as.numeric(converted_result))
                   } else {
                       return(dose_results)
                     }
             }
```

```{r}
 # Function to iterate over each row and apply unit conversion
       compare_and_convert <- function(dose_results, dose_units, einheit_800s, molar_masses) {
           n <- length(dose_results)
           results <- numeric(n)
           
             for (i in 1:n) {
                 results[i] <- compare_and_convert_single(dose_results[i], dose_units[i], einheit_800s[i], molar_masses[i])
               }
           
             return(results)
         }
```

```{r}
           # Merge data tables
             merged.dat <- merge(val.dat, sum.dat, by = "TestOrderCode", all.x = TRUE)
             # Apply the comparison and conversion function row by row
               merged.dat <- merged.dat %>%
                   rowwise() %>%
                   mutate(
                       Result = compare_and_convert_single(DoseResult, DoseUnit, Einheit_800, molar_mass)
                     ) %>%
                   ungroup()
               # View the updated results
                 # print(merged.dat$Result)
                 # print(merged.dat$DoseResult)

val.dat$DoseResult.c <- merged.dat$Result                 
val.dat$DoseUnit.c <- merged.dat$Einheit_800
```

```{r prepare valData SQL TABLE, warning=FALSE, message=FALSE}
# automatically create a SQL TABLE containing DxI9000 data
# function to map R data types to SQLite data types
map.data.types <- function(df) {
  sapply(df, function(column) {
    dtype <- class(column)[1]  # Get the class of the column. If multiple, take the first.
    switch(dtype,
           "factor" = "TEXT",
           "character" = "TEXT",
           "integer" = "INTEGER",
           "numeric" = "REAL",
           "Date" = "TEXT",  # SQLite does not have a DATE type, so dates are often stored as TEXT
           "POSIXct" = "TEXT",  # or as INTEGER (Unix Time)
           "logical" = "INTEGER",  # TRUE/FALSE mapped to 1/0
           "UNKNOWN")  # Default case if type not matched
  })
}

# map data types from val.dat
col.types <- map.data.types(val.dat)

# construct a CREATE TABLE statement for val.dat using the mapped data types
create.table.statement <- paste0("CREATE TABLE IF NOT EXISTS DxIvalData (",
                                paste(
                                  sapply(names(col.types), function(name) paste0('"', name, '"')),
                                  col.types, 
                                  sep=" ", 
                                  collapse=", "),
                                ", ValidationID INTEGER PRIMARY KEY AUTOINCREMENT",
                                ", FOREIGN KEY (Probennummer) REFERENCES MeasurementData (Probennummer)",
                                ")") 

# connect to SQLite DB
con <- dbConnect(SQLite(), dbname = "C:/R_local/labStat/ClinicalChemistry_2.db")

# create the table in the SQLite DB
dbExecute(con, create.table.statement)
```

```{r transfer valData into SQL db, warning=FALSE, message=FALSE}
# insert val.dat into the SQLite DB
dbWriteTable(con, "DxIvalData", val.dat, append = TRUE, row.names = FALSE)
```

```{r}
# for deletion of a table
# dbExecute(con, "DROP TABLE IF EXISTS DxIvalData")

# close the connection
# dbDisconnect(con)
```

```{r BCI_INLAB tranlation into SQL db, warning=FALSE, message=FALSE}

# import BCI_INLAB data
BCI_INLAB <- fread("C:/R_local/autoVal/query_bez_DxI_result.csv", sep = ";", encoding = "UTF-8")
BCI_INLAB$TestOrderCode <- as.integer(BCI_INLAB$TestOrderCode)

# map data types from val.dat
col.types <- map.data.types(BCI_INLAB)

# construct a CREATE TABLE statement for val.dat using the mapped data types
create.table.statement <- paste0("CREATE TABLE IF NOT EXISTS TranslationData (",
                                paste(
                                  sapply(names(col.types), function(name) paste0('"', name, '"')),
                                  col.types, 
                                  sep=" ", 
                                  collapse=", "),
                                ", TranslationID INTEGER PRIMARY KEY AUTOINCREMENT",
                                ", FOREIGN KEY (Methode) REFERENCES MethodData (Methode)",
                                ", FOREIGN KEY (TestOrderCode) REFERENCES DxIvalData (TestOrderCode)",
                                #", UNIQUE (Methode, TestOrderCode)",
                                ")") 

# connect to SQLite DB
con <- dbConnect(SQLite(), dbname = "C:/R_local/labStat/ClinicalChemistry_2.db")

# create the table in the SQLite DB
dbExecute(con, create.table.statement)

# insert val.dat into the SQLite DB
dbWriteTable(con, "TranslationData", BCI_INLAB, append = TRUE, row.names = FALSE)


# for deletion of a table
# dbExecute(con, "DROP TABLE IF EXISTS TranslationData")

dbDisconnect(con)
```

```{r, warning=FALSE, message=FALSE}

# query.dxi.val <- "SELECT DISTINCT a.Methode, 
#                     a.Bezeichnung, 
#                     a.Werte, 
#                     m.EINHEIT, 
#                     t.TestName, 
#                     d.DoseResult, 
#                     d.DoseUnit, 
#                     a.Probennummer, 
#                     d.Probennummer  
#                   FROM MeasurementData a 
#                     JOIN MethodData m ON a.Methode = m.Methode
#                     JOIN TranslationData t ON a.Methode = t.Methode
#                     JOIN DxIvalData d ON t.TestOrderCode = d.TestOrderCode
#                   WHERE a.Bezeichnung = 'Ferritin' AND a.Probennummer = d.Probennummer;"
# 
# con <- dbConnect(SQLite(), dbname = "C:/R_local/labStat/ClinicalChemistry_2.db")
# 
# query.dxi.val <- dbGetQuery(con, query.dxi.val)
# 
# dbDisconnect(con)

# query is further used in DxI_autoValOffcDwnWrd.Rmd

```
